# Generated by Django 6.0.5 on 2026-06-05 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_price_remove_product_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Categorys',
        ),
    ]
